### ISSUE TITLE
subsetMaf causes loss of custom copy number data in returned maf object

### ISSUE THREAD

**Issue by zhujack** [PoisonAlien/maftools#76]
My custom copy number data was read in MAF

   MAF = read.maf(opt$mafFile, clinicalData=opt$clinFile, 
        cnTable=opt$cnTable)

Then, in the following maf object using subsetMaf, the custom copy number data get lost:

   maf = subsetMaf(maf = maf, query = opt$subsetQuery, mafObj = TRUE)
   
Thanks.

Jack

**Comment by zhujack** [comment]
Also, the returned maf object from subsetMaf always has anno.spl.sort error, but the original MAF object does not have any issues:

 oncoplot(maf, top = opt$topN,  clinicalFeatures=clinicalFeatures,
+                   annotationDat=NULL, annotationColor = NULL, genesToIgnore = NULL,
+                   showTumorSampleBarcodes=as.logical(opt$showTumorSampleBarcodes), removeNonMutated=FALSE, colors = NULL,
+                   sortByMutation = FALSE, sortByAnnotation=sortByAnnotation,
+                   annotationOrder = NULL, keepGeneOrder = FALSE, GeneOrderSort = TRUE,
+                   writeMatrix = FALSE, fontSize = 10, SampleNamefontSize = 10,
+                   titleFontSize = 15, legendFontSize = 12)

Error in anno.spl.sort[[i]] : subscript out of bounds
In addition: Warning message:
In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'

**Comment by PoisonAlien** [comment]
Hi,

1. Can you post your `subsetQuery` ?
2. How does `clinicalFeatures` look like in your oncoplot command ?

**Comment by zhujack** [comment]
Hi,
Thanks. I might have missed something, especially the format for custom copy number data.

1. My subsetMaf:

maf = subsetMaf(maf = maf, query = "IMPACT == 'HIGH' | IMPACT == 'MODERATE'", mafObj = TRUE)

2. clinicalFeatures: "case"

3. opt$clinFile:
Tumor_Sample_Barcode	Case
Case10_Metastasis	Case10
Case10_Normal	Case10
Case10_Tumor	Case10
...

4. opt$cnTable (gene names should be the first column?):
D68	Case10_Metastasis	Amp
CDC20B	Case10_Normal	Amp
DSG1	Case10_Tumor	Amp
EPHA7	Case11_Metastasis	Del
...

5. Commands:
MAF = read.maf(opt$mafFile, clinicalData=opt$clinFile,
cnTable=opt$cnTable)
maf = subsetMaf(maf = MAF, query = opt$subsetQuery, mafObj = TRUE)

6. Problems with maf object after subsetMaf and there was no problem with MAF, the original maf object:
1). maf@gene.summary lost copy number columns
2). sortByAnnotation =TRUE will caused Error in anno.spl.sort[[i]] : subscript out of bounds

**Comment by PoisonAlien** [comment]
Hi,

1,5. It makes sense that you're loosing copy number info after subset since you're choosing only the variants where impact columns are either High or Moderate. I guess that copynumber variants do not have these info hence they wont be selected after subset.

2,3,6. Does clinFile contains `Case` information for all samples ?

4. Yes, gene names should be first. https://support.bioconductor.org/p/94113/

**Comment by zhujack** [comment]
Thanks. 
`maf = subsetMaf(maf = MAF, query = " IMPACT == 'HIGH' | IMPACT == 'MODERATE' | Variant_Type == 'CNV' ", mafObj = TRUE)`

Yes, the above code will add back CNV columns after subsetMaf, but it will also pick up all the variants other than 'HIGH' and 'MODERATE' variants. So, in my opinion, ideally subsetMaf will subset the original "'MAF', including the CNV columns if they exist. 

Yes, case field in clinFile includes all the sample.

**Comment by zhujack** [comment]
Hi, 

I have created a small test case for showing the anno.spl.sort error with oncoplot when a subsetted maf is used or clinical data not supplied.

1. Test files:
[test.cnTable.txt](https://github.com/PoisonAlien/maftools/files/1427537/test.cnTable.txt)
[test.clinical.txt](https://github.com/PoisonAlien/maftools/files/1427538/test.clinical.txt)
[test.maf.txt](https://github.com/PoisonAlien/maftools/files/1427542/test.maf.txt)

Note: both the clinical data table and CNV table contain all the samples. 

1. Test 1:  anno.spl.sort error in oncoplot with a subsetted maf object containing both clinical data and CN data:
`MAF = read.maf('test.maf.txt', clinicalData=test.clinical.txt, 
      cnTable='test.cnTable.txt')`
`maf = MAF`
`maf = subsetMaf(maf = MAF, query = "IMPACT == 'HIGH'", mafObj = TRUE)`

No problem with original maf object ('MAF') before subsetting:

` oncoplot(MAF, top = 3, clinicalFeatures='Case',
    sortByAnnotation=TRUE)`

But got anno.spl.sort error with the subsetted maf object ('maf'):

`oncoplot(maf, top = 3, clinicalFeatures='Case',
  sortByAnnotation=TRUE)`

Error in anno.spl.sort[[i]] : subscript out of bounds
In addition: Warning message:
In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'

2. Test 2: when sortByAnnotation=TRUE, anno.spl.sort error in oncoplot with a subseted maf object containing only clinical data:

`MAF = read.maf('test.maf.txt', clinicalData=test.clinical.txt, 
      cnTable=NULL)`
`maf = MAF`
`maf = subsetMaf(maf = MAF, query = "IMPACT == 'HIGH'", mafObj = TRUE)`

`oncoplot(maf, top = 3, clinicalFeatures='Case',
  sortByAnnotation=TRUE)`
`oncoplot(MAF, top = 3, clinicalFeatures='Case',
    sortByAnnotation=TRUE)`
    
Error in anno.spl.sort[[i]] : subscript out of bounds
In addition: Warning message:
In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'

When set sortByAnnotation=FALSE, there is no error.

3. Test 3: when sortByAnnotation=TRUE, anno.spl.sort error in oncoplot without clinical data, no matter subsetting or not:

`MAF = read.maf('test.maf.txt', clinicalData=NULL, 
      cnTable=NULL)`
`maf = MAF`
`maf = subsetMaf(maf = MAF, query = "IMPACT == 'HIGH'", mafObj = TRUE)`

`oncoplot(MAF, top = 3, clinicalFeatures=NULL,
  sortByAnnotation=TRUE)`
`oncoplot(maf, top = 3, clinicalFeatures=NULL,
  sortByAnnotation=TRUE)`

Error in oncoplot(MAF, top = 3, clinicalFeatures = NULL, sortByAnnotation = TRUE) :
  Use argument `annotationCol` to provide at-least one of the annotations.

When set sortByAnnotation=FALSE, there is no error.

So, it looks like clinical data is necessary for oncoplot and subsetting causes anno.spl.sort error.

Thanks.

Jack

**Comment by PoisonAlien** [comment]
Hi,

I think I found the issue and I have fixed it. Can you install from GitHub and test it ?

I have also added an argument `restrictTo` to `subsetMaf`. You can restrict your subset operations to either mutations or CNV. In your case you can do something like this:

```r
MAF = read.maf('~/Downloads/test.maf.txt', clinicalData= '~/Downloads/test.clinical.txt', cnTable='~/Downloads/test.cnTable.txt')

# printing first 5 rows
subsetMaf(maf = MAF, query = " IMPACT == 'HIGH' ", restrictTo = "mutations", fields = "IMPACT")[1:5]     Hugo_Symbol Chromosome Start_Position End_Position Reference_Allele Tumor_Seq_Allele2 Variant_Classification Variant_Type Tumor_Sample_Barcode IMPACT 1: RP11-417J8.6       chr1      142699216    142699218              TAC                 -            Splice_Site          DEL         Case10_Tumor   HIGH 2:         SDHC       chr1      161326488    161326488                C                 A      Nonsense_Mutation          SNP     Case9_Metastasis   HIGH 3:        HMCN1       chr1      186031097    186031097                G                 A            Splice_Site          SNP     Case4_Metastasis   HIGH 4:      COL11A1         NA             NA           NA               NA                NA                    Del          CNV    Case10_Metastasis     NA 5:      FAM19A3         NA             NA           NA               NA                NA                    Amp          CNV     Case2_Metastasis     NA
```

**Comment by zhujack** [comment]
Thanks for fixing the subsetMaf problem and it is working now generally from my test:

1. As default, restrictTo = 'all', still causes subsetMaf to lose CN information and restrictTo = 'mutations' will keep the CN information

2. I wonder if it is possible treat CN data as maf fields and resulting of maf object always has CN data if exists or still exists after subsetting, e.g.

`maf = subsetMaf(maf = MAF, query = "IMPACT == 'HIGH' & CN == 'Del' ", mafObj = TRUE)`

3. Just confirm: should a cnTable always contain CN status for all samples and all genes?

4. Also confirm: should a clinical data table always contain all samples?

**Comment by zhujack** [comment]
Also I would like to confirm the anno.spl.sort error is gone in the new revision.   Thanks.

**Comment by PoisonAlien** [comment]
Hi,

2. for this I think you will have to set `restrictTo = "mutation"` so that you still retain CN data as is. CN data is stored in MAF just like mutations but with `Variant_Type `field set to `CNV` and `Variant_Classification` field set to `Amp` or `Del`. You can subset accordingly using these values. 

```r
maf = subsetMaf(maf = MAF, query = "IMPACT == 'HIGH' & Variant_Type == 'Del' ", mafObj = TRUE)
```

3. Not necessary. You can include whatever genes and samples you want.
4. Again not necessary. Missing samples will be set to NAs. But its always good to have complete data.

Thanks again for the bug report.

**Comment by zhujack** [comment]
I see.  Thanks.  One question: I found color blocks (Pink or Blue) for CN events on a oncoplot seem too big that cover fully color blocks for mutation events for a same gene and same same sample.  I wonder how I can change height of color blocks for CN events. Fro example: 

[mutect.maf.filteredLOG_FISHER-4_IMPACT_H-M.oncoplot_top30.pdf](https://github.com/PoisonAlien/maftools/files/1439140/mutect.maf.filteredLOG_FISHER-4_IMPACT_H-M.oncoplot_top30.pdf)

**Comment by PoisonAlien** [comment]
Hi,
This is bit tricky part, I will see if ComplexHeatmap has any argument for it (I guess there is one). Meanwhile you can try saving the plot with different width or length and see if it helps.

**Comment by zhujack** [comment]
Hi, 

FYI. For the oncoplot, a copy number color bar on the plot always covers a underneath variant color bar if a given sample and gene has both copy number change and variant event.   I modified parameters for width and height for "Del" and "Amp"  in both add_oncoprint and add_oncoprint2 functions to make a copy number color bar smaller:

`  ##Following two funcs add grids
  add_oncoprint = function(type, x, y, width, height) {
    grid::grid.rect(x, y, width * 0.7,
                    height  * 0.6, gp = grid::gpar(col = NA, fill = bg))

    for (i in 1:length(variant.classes)) {
      if (any(type %in% variant.classes[i])) {
        grid::grid.rect(x, y, width * 0.7,
                            height  * 0.6, gp = grid::gpar(col = NA, fill = type_col[variant.classes[i]]))
      } else if (any(type %in% 'Amp')) {
        grid::grid.rect(x, y, width * 0.7,
                          height  * 0.6, gp = grid::gpar(col = NA, fill = bg))
        grid::grid.rect(x, y, width * 0.7,
                          height  * 0.3, gp = grid::gpar(col = NA, fill = type_col['Amp']))
      } else if (any(type %in% 'Del')) {
        grid::grid.rect(x, y, width * 0.7,
                          height  * 0.6, gp = grid::gpar(col = NA, fill = bg))
        grid::grid.rect(x, y, width * 0.7,
                          height  * 0.3, gp = grid::gpar(col = NA, fill = type_col['Del']))
      }
    }
  }

  add_oncoprint2 = function(type, x, y, width, height) {
    for (i in 1:length(variant.classes)) {
      if (any(type %in% variant.classes[i])) {
        grid::grid.rect(x, y, width * 0.7,
                          height  * 0.6, gp = grid::gpar(col = NA, fill = type_col[variant.classes[i]]))
      } else if (any(type %in% 'Amp')) {
        grid::grid.rect(x, y, width * 0.7,
                          height  * 0.3, gp = grid::gpar(col = NA, fill = type_col['Amp']))
      } else if (any(type %in% 'Del')) {

        grid::grid.rect(x, y, width * 0.7,
                          height  * 0.3, gp = grid::gpar(col = NA, fill = type_col['Del']))
      }
    }
  }`

**Comment by PoisonAlien** [comment]
Hi,

Thank for the modification. How does it work when you have smaller or more number of genes ? Does it still maintains the color bar ratio ?
